//All buttons pins
int buttonPin1 = 2;
int buttonPin2 = 3;
int buttonPin3 = 4;
int buttonPin4 = 5;
int buttonPin5 = 7;
int buttonPin6 = 8;
int buttonPin7 = 9;
int buttonPin8 = 10;
int buttonPin9 = 11;
int buttonPin10 = 12;
int buttonPin11 = 13;
int buttonPin12 = 22;
int buttonPin13 = 23;
int buttonPin14 = 24;
int buttonPin15 = 25;
int buttonPin16 = 26;
int buttonPin17 = 27;
int buttonPin18 = 28;
int buttonPin19 = 29;
int buttonPin20 = 30;
int buttonPin21 = 31;
int buttonPin22 = 32;
int buttonPin23 = 33;
int buttonPin24 = 34;
int buttonPin25 = 35;
int buttonPin26 = 36;
int buttonPin27 = 37;
int buttonPin28 = 38;
int buttonPin29 = 39;
int buttonPin30 = 40;
int buttonPin31 = 41;
int buttonPin32 = 42;
int buttonPin33 = 43;
int buttonPin34 = 44;
int buttonPin35 = 45;
int buttonPin36 = 46;
int buttonPin37 = 47;
int buttonPin38 = 48;
int buttonPin39 = 49;
int buttonPin40 = 50;

//All button states
int buttonState1 = 0;
int buttonState2 = 0;
int buttonState3 = 0;
int buttonState4 = 0;
int buttonState5 = 0;
int buttonState6 = 0;
int buttonState7 = 0;
int buttonState8 = 0;
int buttonState9 = 0;
int buttonState10 = 0;
int buttonState11 = 0;
int buttonState12 = 0;
int buttonState13 = 0;
int buttonState14 = 0;
int buttonState15 = 0;
int buttonState16 = 0;
int buttonState17  = 0;
int buttonState18 = 0;
int buttonState19 = 0;
int buttonState20 = 0;
int buttonState21 = 0;
int buttonState22 = 0;
int buttonState23 = 0;
int buttonState24 = 0;
int buttonState25 = 0;
int buttonState26 = 0;
int buttonState27 = 0;
int buttonState28 = 0;
int buttonState29 = 0;
int buttonState30 = 0;
int buttonState31 = 0;
int buttonState32 = 0;
int buttonState33 = 0;
int buttonState34= 0;
int buttonState35 = 0;
int buttonState36 = 0;
int buttonState37 = 0;
int buttonState38 = 0;
int buttonState39 = 0;
int buttonState40 = 0;

void setup() {
  //Create vertual buttons
  pinMode(buttonPin1, INPUT);
  pinMode(buttonPin2, INPUT);
  pinMode(buttonPin3, INPUT);
  pinMode(buttonPin4, INPUT);
  pinMode(buttonPin5, INPUT);
  pinMode(buttonPin6, INPUT);
  pinMode(buttonPin7, INPUT);
  pinMode(buttonPin8, INPUT);
  pinMode(buttonPin9, INPUT);
  pinMode(buttonPin10, INPUT);
  pinMode(buttonPin11, INPUT);
  pinMode(buttonPin12, INPUT);
  pinMode(buttonPin13, INPUT);
  pinMode(buttonPin14, INPUT);
  pinMode(buttonPin15, INPUT);
  pinMode(buttonPin16, INPUT);
  pinMode(buttonPin17, INPUT);
  pinMode(buttonPin18, INPUT);
  pinMode(buttonPin19, INPUT);
  pinMode(buttonPin20, INPUT);
  pinMode(buttonPin21, INPUT);
  pinMode(buttonPin22, INPUT);
  pinMode(buttonPin23, INPUT);
  pinMode(buttonPin24, INPUT);
  pinMode(buttonPin25, INPUT);
  pinMode(buttonPin26, INPUT);
  pinMode(buttonPin27, INPUT);
  pinMode(buttonPin28, INPUT);
  pinMode(buttonPin29, INPUT);
  pinMode(buttonPin30, INPUT);
  pinMode(buttonPin31, INPUT);
  pinMode(buttonPin32, INPUT);
  pinMode(buttonPin33, INPUT);
  pinMode(buttonPin34, INPUT);
  pinMode(buttonPin35, INPUT);
  pinMode(buttonPin36, INPUT);
  pinMode(buttonPin37, INPUT);
  pinMode(buttonPin38, INPUT);
  pinMode(buttonPin39, INPUT);
  pinMode(buttonPin40, INPUT);
}

void loop() {
  //Read all buttons for input
  buttonState2 = digitalRead(buttonPin1);
  buttonState2 = digitalRead(buttonPin1);
  buttonState3 = digitalRead(buttonPin1);
  buttonState4 = digitalRead(buttonPin1);
  buttonState5 = digitalRead(buttonPin1);
  buttonState6 = digitalRead(buttonPin1);
  buttonState7 = digitalRead(buttonPin1);
  buttonState8 = digitalRead(buttonPin1);
  buttonState9 = digitalRead(buttonPin1);
  buttonState10 = digitalRead(buttonPin1);
  buttonState11 = digitalRead(buttonPin1);
  buttonState12 = digitalRead(buttonPin1);
  buttonState13 = digitalRead(buttonPin1);
  buttonState14 = digitalRead(buttonPin1);
  buttonState15 = digitalRead(buttonPin1);
  buttonState16 = digitalRead(buttonPin1);
  buttonState17 = digitalRead(buttonPin1);
  buttonState18 = digitalRead(buttonPin1);
  buttonState19 = digitalRead(buttonPin1);
  buttonState20 = digitalRead(buttonPin1);
  buttonState21 = digitalRead(buttonPin1);
  buttonState22 = digitalRead(buttonPin1);
  buttonState23 = digitalRead(buttonPin1);
  buttonState24 = digitalRead(buttonPin1);
  buttonState25 = digitalRead(buttonPin1);
  buttonState26 = digitalRead(buttonPin1);
  buttonState27 = digitalRead(buttonPin1);
  buttonState28 = digitalRead(buttonPin1);
  buttonState29 = digitalRead(buttonPin1);
  buttonState30 = digitalRead(buttonPin1);
  buttonState31 = digitalRead(buttonPin1);
  buttonState32 = digitalRead(buttonPin1);
  buttonState33 = digitalRead(buttonPin1);
  buttonState34 = digitalRead(buttonPin1);
  buttonState35 = digitalRead(buttonPin1);
  buttonState36 = digitalRead(buttonPin1);
  buttonState37 = digitalRead(buttonPin1);
  buttonState38 = digitalRead(buttonPin1);
  buttonState39 = digitalRead(buttonPin1);
  buttonState40 = digitalRead(buttonPin1);

}
